### ISSUE TITLE
data for package map

### ISSUE THREAD

**Issue by Kenkleinman** [Kenkleinman/clusterPower#199]

**Comment by alexandria-sakrejda** [comment]
I wrote you a helpful function to do this. "package_map_helper()". It's an external function, but there is no .rd documentation since it's just for you... I just wanted to put it somewhere where you would be able to find it. Documentation is available in the source code, though. You can use it on other packages, but the default is "clusterPower".

**Comment by Kenkleinman** [comment]
Nice!!!
_______________________________________________________
_______________________________________________________
Ken Kleinman, ScD
Professor, Department of Biostatistics and Epidemiology
School of Public Health and Health Sciences
University of Massachusetts, Amherst

Lecturer, Department of Population Medicine
Harvard Medical School

My home page: http://www.kleinman.science
My blog on SAS and R: http://sas-and-r.blogspot.com
My cites on Google Scholar: http://tinyurl.com/KenK-cites
__________________________________________________
Proud member of the Massachusetts Society of Professors (MSP/MTA/NEA), the
union representing faculty and librarians at UMass Amherst: umassmsp.org
